package Relax.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum DateFormatTypes {
  DAY_MONTH_YEAR("DAY.MONTH.YEAR", "\"dd.mm.yyyy\""),
  MONTH_DAY_YEAR("MONTH/DAY/YEAR", "\"mm/dd/yyyy\"");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private DateFormatTypes(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<DateFormatTypes> getConstants() {
    List<DateFormatTypes> list = ListSequence.fromList(new LinkedList<DateFormatTypes>());
    ListSequence.fromList(list).addElement(DateFormatTypes.DAY_MONTH_YEAR);
    ListSequence.fromList(list).addElement(DateFormatTypes.MONTH_DAY_YEAR);
    return list;
  }
  public static DateFormatTypes getDefault() {
    return DateFormatTypes.DAY_MONTH_YEAR;
  }
  public static DateFormatTypes parseValue(String value) {
    if (value == null) {
      return DateFormatTypes.getDefault();
    }
    if (value.equals(DateFormatTypes.DAY_MONTH_YEAR.getValueAsString())) {
      return DateFormatTypes.DAY_MONTH_YEAR;
    }
    if (value.equals(DateFormatTypes.MONTH_DAY_YEAR.getValueAsString())) {
      return DateFormatTypes.MONTH_DAY_YEAR;
    }
    return DateFormatTypes.getDefault();
  }
}
